### ISSUE TITLE
Multiple Checklist

### ISSUE THREAD

**Issue by christian1koch** [christian1koch/checklist#1]
Create feature to support multiple checklists
- [x] Checklist should be able to be created with name
- [ ] #9
- [x] should show the list of checklists somehow
- [x] clicking on a checklist should move to that checklist page, with the checlist name as title
- [ ] #10
- [ ] #11

In the future I would like to add more customization to them (custom bg-colors, tags, etc)

**Comment by christian1koch** [comment]
Also add colors!
